### ISSUE TITLE
Does it work for windows 10, and how to operate after installation?

### ISSUE THREAD

**Issue by EvitanRelta** [xkjyeah/itf-unicode-db#1]
Hi,
I stumbled upon ur ITF unicode db project and quite like the idea. But you didn't really state the OS that it supports so I was wondering does it support Windows 10?
I tried downloading it on my Win10 at 
https://sourceforge.net/projects/itf-unicode-db/files/
but after installing, Ctrl+Shift+U didn't seem to do anything, and idk if I needed to run the program first or something.
Mind helping me out?

Thanks!

**Comment by xkjyeah** [comment]
Yes it does. After installation, you should see an extra option appear on
your input method switcher (or Windows key+ Space). Only after you've
switched to the ITF Unicode dB IME will you be able to use the Ctrl+Shift+U
shortcut

**Comment by EvitanRelta** [comment]
Alright its working now, thanks for the help!
